# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import step7_pb2 as step7__pb2


class Step7Stub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreateProject = channel.unary_unary(
        '/step7service.Step7/CreateProject',
        request_serializer=step7__pb2.CreateProjectRequest.SerializeToString,
        response_deserializer=step7__pb2.StatusReply.FromString,
        )
    self.CreateLibrary = channel.unary_unary(
        '/step7service.Step7/CreateLibrary',
        request_serializer=step7__pb2.CreateLibraryRequest.SerializeToString,
        response_deserializer=step7__pb2.StatusReply.FromString,
        )
    self.RegisterProject = channel.unary_unary(
        '/step7service.Step7/RegisterProject',
        request_serializer=step7__pb2.RegisterProjectRequest.SerializeToString,
        response_deserializer=step7__pb2.StatusReply.FromString,
        )
    self.RemoveProject = channel.unary_unary(
        '/step7service.Step7/RemoveProject',
        request_serializer=step7__pb2.RemoveProjectRequest.SerializeToString,
        response_deserializer=step7__pb2.StatusReply.FromString,
        )
    self.ImportSource = channel.unary_unary(
        '/step7service.Step7/ImportSource',
        request_serializer=step7__pb2.ImportSourceRequest.SerializeToString,
        response_deserializer=step7__pb2.StatusReply.FromString,
        )
    self.ImportSourcesDir = channel.unary_unary(
        '/step7service.Step7/ImportSourcesDir',
        request_serializer=step7__pb2.ImportSourcesDirRequest.SerializeToString,
        response_deserializer=step7__pb2.StatusReply.FromString,
        )
    self.ImportLibSources = channel.unary_unary(
        '/step7service.Step7/ImportLibSources',
        request_serializer=step7__pb2.ImportLibSourcesRequest.SerializeToString,
        response_deserializer=step7__pb2.StatusReply.FromString,
        )
    self.ExportSouce = channel.unary_unary(
        '/step7service.Step7/ExportSouce',
        request_serializer=step7__pb2.ExportSourceRequest.SerializeToString,
        response_deserializer=step7__pb2.StatusReply.FromString,
        )
    self.ExportAllSources = channel.unary_unary(
        '/step7service.Step7/ExportAllSources',
        request_serializer=step7__pb2.ExportAllSourcesRequest.SerializeToString,
        response_deserializer=step7__pb2.StatusReply.FromString,
        )
    self.CompileSource = channel.unary_unary(
        '/step7service.Step7/CompileSource',
        request_serializer=step7__pb2.CompileSourceRequest.SerializeToString,
        response_deserializer=step7__pb2.StatusReply.FromString,
        )
    self.ImportLibBlocks = channel.unary_unary(
        '/step7service.Step7/ImportLibBlocks',
        request_serializer=step7__pb2.ImportLibBlocksRequest.SerializeToString,
        response_deserializer=step7__pb2.StatusReply.FromString,
        )
    self.ImportSymbols = channel.unary_unary(
        '/step7service.Step7/ImportSymbols',
        request_serializer=step7__pb2.ImportSymbolsRequest.SerializeToString,
        response_deserializer=step7__pb2.StatusReply.FromString,
        )
    self.ExportSymbols = channel.unary_unary(
        '/step7service.Step7/ExportSymbols',
        request_serializer=step7__pb2.ExportSymbolsRequest.SerializeToString,
        response_deserializer=step7__pb2.StatusReply.FromString,
        )
    self.CompileAllStations = channel.unary_unary(
        '/step7service.Step7/CompileAllStations',
        request_serializer=step7__pb2.CompileAllStationsRequest.SerializeToString,
        response_deserializer=step7__pb2.StatusReply.FromString,
        )
    self.ListProjects = channel.unary_unary(
        '/step7service.Step7/ListProjects',
        request_serializer=step7__pb2.ListProjectsRequest.SerializeToString,
        response_deserializer=step7__pb2.ListReply.FromString,
        )
    self.ListPrograms = channel.unary_unary(
        '/step7service.Step7/ListPrograms',
        request_serializer=step7__pb2.ListProgramsRequest.SerializeToString,
        response_deserializer=step7__pb2.ListReply.FromString,
        )
    self.ListStations = channel.unary_unary(
        '/step7service.Step7/ListStations',
        request_serializer=step7__pb2.ListStationsRequest.SerializeToString,
        response_deserializer=step7__pb2.ListReply.FromString,
        )
    self.ListContainers = channel.unary_unary(
        '/step7service.Step7/ListContainers',
        request_serializer=step7__pb2.ListContainersRequest.SerializeToString,
        response_deserializer=step7__pb2.ListReply.FromString,
        )
    self.StartProgram = channel.unary_unary(
        '/step7service.Step7/StartProgram',
        request_serializer=step7__pb2.ProgramRequest.SerializeToString,
        response_deserializer=step7__pb2.StatusReply.FromString,
        )
    self.StopProgram = channel.unary_unary(
        '/step7service.Step7/StopProgram',
        request_serializer=step7__pb2.ProgramRequest.SerializeToString,
        response_deserializer=step7__pb2.StatusReply.FromString,
        )
    self.DownloadProgramBlocks = channel.unary_unary(
        '/step7service.Step7/DownloadProgramBlocks',
        request_serializer=step7__pb2.DownloadProgramBlocksRequest.SerializeToString,
        response_deserializer=step7__pb2.StatusReply.FromString,
        )


class Step7Servicer(object):
  # missing associated documentation comment in .proto file
  pass

  def CreateProject(self, request, context):
    """Create new empty STEP 7 project
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateLibrary(self, request, context):
    """Create new empty STEP 7 library
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RegisterProject(self, request, context):
    """Registers existing STEP 7 project
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RemoveProject(self, request, context):
    """Removes STEP 7 project and deletes all of its files
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ImportSource(self, request, context):
    """Import source into a program
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ImportSourcesDir(self, request, context):
    """Import sources from a directory into a project
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ImportLibSources(self, request, context):
    """Import sources from a library into project
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ExportSouce(self, request, context):
    """Exports a source from a program to a directory
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ExportAllSources(self, request, context):
    """Exports all sources from a program to a directory
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CompileSource(self, request, context):
    """Compile specified source code module
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ImportLibBlocks(self, request, context):
    """Import blocks from a library into project
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ImportSymbols(self, request, context):
    """Imports symbols into a program from a file
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ExportSymbols(self, request, context):
    """Exports symbols from program from into a file
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CompileAllStations(self, request, context):
    """Compiles the HW configuration for each of the stations in a project
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListProjects(self, request, context):
    """TODO: List functions could return better replies with more data...

    Creates list with project names
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListPrograms(self, request, context):
    """Creates list with programs in a given project
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListStations(self, request, context):
    """Creates list with stations in a given project
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListContainers(self, request, context):
    """Creates list with containers for each program in a given project
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def StartProgram(self, request, context):
    """[ONLINE] Starts/restarts a program
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def StopProgram(self, request, context):
    """[ONLINE] Stops a program
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DownloadProgramBlocks(self, request, context):
    """[ONLINE] Downloads all the blocks under a Program
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_Step7Servicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CreateProject': grpc.unary_unary_rpc_method_handler(
          servicer.CreateProject,
          request_deserializer=step7__pb2.CreateProjectRequest.FromString,
          response_serializer=step7__pb2.StatusReply.SerializeToString,
      ),
      'CreateLibrary': grpc.unary_unary_rpc_method_handler(
          servicer.CreateLibrary,
          request_deserializer=step7__pb2.CreateLibraryRequest.FromString,
          response_serializer=step7__pb2.StatusReply.SerializeToString,
      ),
      'RegisterProject': grpc.unary_unary_rpc_method_handler(
          servicer.RegisterProject,
          request_deserializer=step7__pb2.RegisterProjectRequest.FromString,
          response_serializer=step7__pb2.StatusReply.SerializeToString,
      ),
      'RemoveProject': grpc.unary_unary_rpc_method_handler(
          servicer.RemoveProject,
          request_deserializer=step7__pb2.RemoveProjectRequest.FromString,
          response_serializer=step7__pb2.StatusReply.SerializeToString,
      ),
      'ImportSource': grpc.unary_unary_rpc_method_handler(
          servicer.ImportSource,
          request_deserializer=step7__pb2.ImportSourceRequest.FromString,
          response_serializer=step7__pb2.StatusReply.SerializeToString,
      ),
      'ImportSourcesDir': grpc.unary_unary_rpc_method_handler(
          servicer.ImportSourcesDir,
          request_deserializer=step7__pb2.ImportSourcesDirRequest.FromString,
          response_serializer=step7__pb2.StatusReply.SerializeToString,
      ),
      'ImportLibSources': grpc.unary_unary_rpc_method_handler(
          servicer.ImportLibSources,
          request_deserializer=step7__pb2.ImportLibSourcesRequest.FromString,
          response_serializer=step7__pb2.StatusReply.SerializeToString,
      ),
      'ExportSouce': grpc.unary_unary_rpc_method_handler(
          servicer.ExportSouce,
          request_deserializer=step7__pb2.ExportSourceRequest.FromString,
          response_serializer=step7__pb2.StatusReply.SerializeToString,
      ),
      'ExportAllSources': grpc.unary_unary_rpc_method_handler(
          servicer.ExportAllSources,
          request_deserializer=step7__pb2.ExportAllSourcesRequest.FromString,
          response_serializer=step7__pb2.StatusReply.SerializeToString,
      ),
      'CompileSource': grpc.unary_unary_rpc_method_handler(
          servicer.CompileSource,
          request_deserializer=step7__pb2.CompileSourceRequest.FromString,
          response_serializer=step7__pb2.StatusReply.SerializeToString,
      ),
      'ImportLibBlocks': grpc.unary_unary_rpc_method_handler(
          servicer.ImportLibBlocks,
          request_deserializer=step7__pb2.ImportLibBlocksRequest.FromString,
          response_serializer=step7__pb2.StatusReply.SerializeToString,
      ),
      'ImportSymbols': grpc.unary_unary_rpc_method_handler(
          servicer.ImportSymbols,
          request_deserializer=step7__pb2.ImportSymbolsRequest.FromString,
          response_serializer=step7__pb2.StatusReply.SerializeToString,
      ),
      'ExportSymbols': grpc.unary_unary_rpc_method_handler(
          servicer.ExportSymbols,
          request_deserializer=step7__pb2.ExportSymbolsRequest.FromString,
          response_serializer=step7__pb2.StatusReply.SerializeToString,
      ),
      'CompileAllStations': grpc.unary_unary_rpc_method_handler(
          servicer.CompileAllStations,
          request_deserializer=step7__pb2.CompileAllStationsRequest.FromString,
          response_serializer=step7__pb2.StatusReply.SerializeToString,
      ),
      'ListProjects': grpc.unary_unary_rpc_method_handler(
          servicer.ListProjects,
          request_deserializer=step7__pb2.ListProjectsRequest.FromString,
          response_serializer=step7__pb2.ListReply.SerializeToString,
      ),
      'ListPrograms': grpc.unary_unary_rpc_method_handler(
          servicer.ListPrograms,
          request_deserializer=step7__pb2.ListProgramsRequest.FromString,
          response_serializer=step7__pb2.ListReply.SerializeToString,
      ),
      'ListStations': grpc.unary_unary_rpc_method_handler(
          servicer.ListStations,
          request_deserializer=step7__pb2.ListStationsRequest.FromString,
          response_serializer=step7__pb2.ListReply.SerializeToString,
      ),
      'ListContainers': grpc.unary_unary_rpc_method_handler(
          servicer.ListContainers,
          request_deserializer=step7__pb2.ListContainersRequest.FromString,
          response_serializer=step7__pb2.ListReply.SerializeToString,
      ),
      'StartProgram': grpc.unary_unary_rpc_method_handler(
          servicer.StartProgram,
          request_deserializer=step7__pb2.ProgramRequest.FromString,
          response_serializer=step7__pb2.StatusReply.SerializeToString,
      ),
      'StopProgram': grpc.unary_unary_rpc_method_handler(
          servicer.StopProgram,
          request_deserializer=step7__pb2.ProgramRequest.FromString,
          response_serializer=step7__pb2.StatusReply.SerializeToString,
      ),
      'DownloadProgramBlocks': grpc.unary_unary_rpc_method_handler(
          servicer.DownloadProgramBlocks,
          request_deserializer=step7__pb2.DownloadProgramBlocksRequest.FromString,
          response_serializer=step7__pb2.StatusReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'step7service.Step7', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
