# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: step7.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='step7.proto',
  package='step7service',
  syntax='proto3',
  serialized_options=b'\n\005step7B\005Step7P\001\242\002\002S7',
  serialized_pb=b'\n\x0bstep7.proto\x12\x0cstep7service\"!\n\x0eProjectRequest\x12\x0f\n\x07project\x18\x01 \x01(\t\"?\n\x14\x43reateProjectRequest\x12\x13\n\x0bprojectName\x18\x01 \x01(\t\x12\x12\n\nprojectDir\x18\x02 \x01(\t\"p\n\x10ImportLibRequest\x12\x0f\n\x07project\x18\x01 \x01(\t\x12\x0f\n\x07program\x18\x02 \x01(\t\x12\x13\n\x0blibraryName\x18\x03 \x01(\t\x12\x16\n\x0elibraryProgram\x18\x04 \x01(\t\x12\r\n\x05\x66orce\x18\x05 \x01(\x08\"I\n\x14ImportSymbolsRequest\x12\x0f\n\x07project\x18\x01 \x01(\t\x12\x0f\n\x07program\x18\x02 \x01(\t\x12\x0f\n\x07symbols\x18\x03 \x01(\t\"^\n\x17ImportSourcesDirRequest\x12\x0f\n\x07project\x18\x01 \x01(\t\x12\x0f\n\x07program\x18\x02 \x01(\t\x12\x12\n\nsourcesDir\x18\x03 \x01(\t\x12\r\n\x05\x66orce\x18\x04 \x01(\x08\"J\n\x15\x43ompileSourcesRequest\x12\x0f\n\x07project\x18\x01 \x01(\t\x12\x0f\n\x07program\x18\x02 \x01(\t\x12\x0f\n\x07sources\x18\x03 \x03(\t\"\x1f\n\x0bStatusReply\x12\x10\n\x08\x65xitCode\x18\x01 \x01(\x05\"H\n\tListReply\x12)\n\x06status\x18\x01 \x01(\x0b\x32\x19.step7service.StatusReply\x12\x10\n\x08listItem\x18\x02 \x03(\t2\xc6\x04\n\x05Step7\x12P\n\rCreateProject\x12\".step7service.CreateProjectRequest\x1a\x19.step7service.StatusReply\"\x00\x12O\n\x10ImportLibSources\x12\x1e.step7service.ImportLibRequest\x1a\x19.step7service.StatusReply\"\x00\x12N\n\x0fImportLibBlocks\x12\x1e.step7service.ImportLibRequest\x1a\x19.step7service.StatusReply\"\x00\x12P\n\rImportSymbols\x12\".step7service.ImportSymbolsRequest\x1a\x19.step7service.StatusReply\"\x00\x12V\n\x10ImportSourcesDir\x12%.step7service.ImportSourcesDirRequest\x1a\x19.step7service.StatusReply\"\x00\x12R\n\x0e\x43ompileSources\x12#.step7service.CompileSourcesRequest\x1a\x19.step7service.StatusReply\"\x00\x12L\n\x11GetListOfPrograms\x12\x1c.step7service.ProjectRequest\x1a\x17.step7service.ListReply\"\x00\x42\x15\n\x05step7B\x05Step7P\x01\xa2\x02\x02S7b\x06proto3'
)




_PROJECTREQUEST = _descriptor.Descriptor(
  name='ProjectRequest',
  full_name='step7service.ProjectRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='project', full_name='step7service.ProjectRequest.project', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=62,
)


_CREATEPROJECTREQUEST = _descriptor.Descriptor(
  name='CreateProjectRequest',
  full_name='step7service.CreateProjectRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='projectName', full_name='step7service.CreateProjectRequest.projectName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='projectDir', full_name='step7service.CreateProjectRequest.projectDir', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=64,
  serialized_end=127,
)


_IMPORTLIBREQUEST = _descriptor.Descriptor(
  name='ImportLibRequest',
  full_name='step7service.ImportLibRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='project', full_name='step7service.ImportLibRequest.project', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='program', full_name='step7service.ImportLibRequest.program', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='libraryName', full_name='step7service.ImportLibRequest.libraryName', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='libraryProgram', full_name='step7service.ImportLibRequest.libraryProgram', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='force', full_name='step7service.ImportLibRequest.force', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=129,
  serialized_end=241,
)


_IMPORTSYMBOLSREQUEST = _descriptor.Descriptor(
  name='ImportSymbolsRequest',
  full_name='step7service.ImportSymbolsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='project', full_name='step7service.ImportSymbolsRequest.project', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='program', full_name='step7service.ImportSymbolsRequest.program', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='symbols', full_name='step7service.ImportSymbolsRequest.symbols', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=243,
  serialized_end=316,
)


_IMPORTSOURCESDIRREQUEST = _descriptor.Descriptor(
  name='ImportSourcesDirRequest',
  full_name='step7service.ImportSourcesDirRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='project', full_name='step7service.ImportSourcesDirRequest.project', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='program', full_name='step7service.ImportSourcesDirRequest.program', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sourcesDir', full_name='step7service.ImportSourcesDirRequest.sourcesDir', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='force', full_name='step7service.ImportSourcesDirRequest.force', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=318,
  serialized_end=412,
)


_COMPILESOURCESREQUEST = _descriptor.Descriptor(
  name='CompileSourcesRequest',
  full_name='step7service.CompileSourcesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='project', full_name='step7service.CompileSourcesRequest.project', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='program', full_name='step7service.CompileSourcesRequest.program', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sources', full_name='step7service.CompileSourcesRequest.sources', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=414,
  serialized_end=488,
)


_STATUSREPLY = _descriptor.Descriptor(
  name='StatusReply',
  full_name='step7service.StatusReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='exitCode', full_name='step7service.StatusReply.exitCode', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=490,
  serialized_end=521,
)


_LISTREPLY = _descriptor.Descriptor(
  name='ListReply',
  full_name='step7service.ListReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='step7service.ListReply.status', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='listItem', full_name='step7service.ListReply.listItem', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=523,
  serialized_end=595,
)

_LISTREPLY.fields_by_name['status'].message_type = _STATUSREPLY
DESCRIPTOR.message_types_by_name['ProjectRequest'] = _PROJECTREQUEST
DESCRIPTOR.message_types_by_name['CreateProjectRequest'] = _CREATEPROJECTREQUEST
DESCRIPTOR.message_types_by_name['ImportLibRequest'] = _IMPORTLIBREQUEST
DESCRIPTOR.message_types_by_name['ImportSymbolsRequest'] = _IMPORTSYMBOLSREQUEST
DESCRIPTOR.message_types_by_name['ImportSourcesDirRequest'] = _IMPORTSOURCESDIRREQUEST
DESCRIPTOR.message_types_by_name['CompileSourcesRequest'] = _COMPILESOURCESREQUEST
DESCRIPTOR.message_types_by_name['StatusReply'] = _STATUSREPLY
DESCRIPTOR.message_types_by_name['ListReply'] = _LISTREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ProjectRequest = _reflection.GeneratedProtocolMessageType('ProjectRequest', (_message.Message,), {
  'DESCRIPTOR' : _PROJECTREQUEST,
  '__module__' : 'step7_pb2'
  # @@protoc_insertion_point(class_scope:step7service.ProjectRequest)
  })
_sym_db.RegisterMessage(ProjectRequest)

CreateProjectRequest = _reflection.GeneratedProtocolMessageType('CreateProjectRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATEPROJECTREQUEST,
  '__module__' : 'step7_pb2'
  # @@protoc_insertion_point(class_scope:step7service.CreateProjectRequest)
  })
_sym_db.RegisterMessage(CreateProjectRequest)

ImportLibRequest = _reflection.GeneratedProtocolMessageType('ImportLibRequest', (_message.Message,), {
  'DESCRIPTOR' : _IMPORTLIBREQUEST,
  '__module__' : 'step7_pb2'
  # @@protoc_insertion_point(class_scope:step7service.ImportLibRequest)
  })
_sym_db.RegisterMessage(ImportLibRequest)

ImportSymbolsRequest = _reflection.GeneratedProtocolMessageType('ImportSymbolsRequest', (_message.Message,), {
  'DESCRIPTOR' : _IMPORTSYMBOLSREQUEST,
  '__module__' : 'step7_pb2'
  # @@protoc_insertion_point(class_scope:step7service.ImportSymbolsRequest)
  })
_sym_db.RegisterMessage(ImportSymbolsRequest)

ImportSourcesDirRequest = _reflection.GeneratedProtocolMessageType('ImportSourcesDirRequest', (_message.Message,), {
  'DESCRIPTOR' : _IMPORTSOURCESDIRREQUEST,
  '__module__' : 'step7_pb2'
  # @@protoc_insertion_point(class_scope:step7service.ImportSourcesDirRequest)
  })
_sym_db.RegisterMessage(ImportSourcesDirRequest)

CompileSourcesRequest = _reflection.GeneratedProtocolMessageType('CompileSourcesRequest', (_message.Message,), {
  'DESCRIPTOR' : _COMPILESOURCESREQUEST,
  '__module__' : 'step7_pb2'
  # @@protoc_insertion_point(class_scope:step7service.CompileSourcesRequest)
  })
_sym_db.RegisterMessage(CompileSourcesRequest)

StatusReply = _reflection.GeneratedProtocolMessageType('StatusReply', (_message.Message,), {
  'DESCRIPTOR' : _STATUSREPLY,
  '__module__' : 'step7_pb2'
  # @@protoc_insertion_point(class_scope:step7service.StatusReply)
  })
_sym_db.RegisterMessage(StatusReply)

ListReply = _reflection.GeneratedProtocolMessageType('ListReply', (_message.Message,), {
  'DESCRIPTOR' : _LISTREPLY,
  '__module__' : 'step7_pb2'
  # @@protoc_insertion_point(class_scope:step7service.ListReply)
  })
_sym_db.RegisterMessage(ListReply)


DESCRIPTOR._options = None

_STEP7 = _descriptor.ServiceDescriptor(
  name='Step7',
  full_name='step7service.Step7',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=598,
  serialized_end=1180,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateProject',
    full_name='step7service.Step7.CreateProject',
    index=0,
    containing_service=None,
    input_type=_CREATEPROJECTREQUEST,
    output_type=_STATUSREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ImportLibSources',
    full_name='step7service.Step7.ImportLibSources',
    index=1,
    containing_service=None,
    input_type=_IMPORTLIBREQUEST,
    output_type=_STATUSREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ImportLibBlocks',
    full_name='step7service.Step7.ImportLibBlocks',
    index=2,
    containing_service=None,
    input_type=_IMPORTLIBREQUEST,
    output_type=_STATUSREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ImportSymbols',
    full_name='step7service.Step7.ImportSymbols',
    index=3,
    containing_service=None,
    input_type=_IMPORTSYMBOLSREQUEST,
    output_type=_STATUSREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ImportSourcesDir',
    full_name='step7service.Step7.ImportSourcesDir',
    index=4,
    containing_service=None,
    input_type=_IMPORTSOURCESDIRREQUEST,
    output_type=_STATUSREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CompileSources',
    full_name='step7service.Step7.CompileSources',
    index=5,
    containing_service=None,
    input_type=_COMPILESOURCESREQUEST,
    output_type=_STATUSREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetListOfPrograms',
    full_name='step7service.Step7.GetListOfPrograms',
    index=6,
    containing_service=None,
    input_type=_PROJECTREQUEST,
    output_type=_LISTREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_STEP7)

DESCRIPTOR.services_by_name['Step7'] = _STEP7

# @@protoc_insertion_point(module_scope)
