# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import step7_pb2 as step7__pb2


class Step7Stub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreateProject = channel.unary_unary(
        '/step7service.Step7/CreateProject',
        request_serializer=step7__pb2.CreateProjectRequest.SerializeToString,
        response_deserializer=step7__pb2.StatusReply.FromString,
        )
    self.ImportLibSources = channel.unary_unary(
        '/step7service.Step7/ImportLibSources',
        request_serializer=step7__pb2.ImportLibRequest.SerializeToString,
        response_deserializer=step7__pb2.StatusReply.FromString,
        )
    self.ImportLibBlocks = channel.unary_unary(
        '/step7service.Step7/ImportLibBlocks',
        request_serializer=step7__pb2.ImportLibRequest.SerializeToString,
        response_deserializer=step7__pb2.StatusReply.FromString,
        )
    self.ImportSymbols = channel.unary_unary(
        '/step7service.Step7/ImportSymbols',
        request_serializer=step7__pb2.ImportSymbolsRequest.SerializeToString,
        response_deserializer=step7__pb2.StatusReply.FromString,
        )
    self.ImportSourcesDir = channel.unary_unary(
        '/step7service.Step7/ImportSourcesDir',
        request_serializer=step7__pb2.ImportSourcesDirRequest.SerializeToString,
        response_deserializer=step7__pb2.StatusReply.FromString,
        )
    self.CompileSources = channel.unary_unary(
        '/step7service.Step7/CompileSources',
        request_serializer=step7__pb2.CompileSourcesRequest.SerializeToString,
        response_deserializer=step7__pb2.StatusReply.FromString,
        )
    self.GetListOfPrograms = channel.unary_unary(
        '/step7service.Step7/GetListOfPrograms',
        request_serializer=step7__pb2.ProjectRequest.SerializeToString,
        response_deserializer=step7__pb2.ListReply.FromString,
        )


class Step7Servicer(object):
  # missing associated documentation comment in .proto file
  pass

  def CreateProject(self, request, context):
    """Creates and registers an empty STEP 7 project
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ImportLibSources(self, request, context):
    """Import sources from a library into project
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ImportLibBlocks(self, request, context):
    """Import blocks from a library into project
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ImportSymbols(self, request, context):
    """Import symbols from an sdf file into project
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ImportSourcesDir(self, request, context):
    """Import sources from a directory into a project
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CompileSources(self, request, context):
    """Compile specified source code module(s)
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetListOfPrograms(self, request, context):
    """Gets list of programs in a STEP 7 project
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_Step7Servicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CreateProject': grpc.unary_unary_rpc_method_handler(
          servicer.CreateProject,
          request_deserializer=step7__pb2.CreateProjectRequest.FromString,
          response_serializer=step7__pb2.StatusReply.SerializeToString,
      ),
      'ImportLibSources': grpc.unary_unary_rpc_method_handler(
          servicer.ImportLibSources,
          request_deserializer=step7__pb2.ImportLibRequest.FromString,
          response_serializer=step7__pb2.StatusReply.SerializeToString,
      ),
      'ImportLibBlocks': grpc.unary_unary_rpc_method_handler(
          servicer.ImportLibBlocks,
          request_deserializer=step7__pb2.ImportLibRequest.FromString,
          response_serializer=step7__pb2.StatusReply.SerializeToString,
      ),
      'ImportSymbols': grpc.unary_unary_rpc_method_handler(
          servicer.ImportSymbols,
          request_deserializer=step7__pb2.ImportSymbolsRequest.FromString,
          response_serializer=step7__pb2.StatusReply.SerializeToString,
      ),
      'ImportSourcesDir': grpc.unary_unary_rpc_method_handler(
          servicer.ImportSourcesDir,
          request_deserializer=step7__pb2.ImportSourcesDirRequest.FromString,
          response_serializer=step7__pb2.StatusReply.SerializeToString,
      ),
      'CompileSources': grpc.unary_unary_rpc_method_handler(
          servicer.CompileSources,
          request_deserializer=step7__pb2.CompileSourcesRequest.FromString,
          response_serializer=step7__pb2.StatusReply.SerializeToString,
      ),
      'GetListOfPrograms': grpc.unary_unary_rpc_method_handler(
          servicer.GetListOfPrograms,
          request_deserializer=step7__pb2.ProjectRequest.FromString,
          response_serializer=step7__pb2.ListReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'step7service.Step7', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
