variables:
  NUGET_PATH: 'C:\Tools\Nuget\nuget.exe'
  MSBUILD_PATH: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe'
  PYTHON_VENV_PATH: 'C:\Tools\venv\Scripts\activate.ps1'
  VSTEST_PATH: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\Extensions\TestPlatform\vstest.console.exe'

stages:
  - build
  - test

build_job:
  stage: build
  script:
    - echo $CI_JOB_ID
    - echo $CI_JOB_TAG 
    # Generate correct shared assembly version configuration
    - '& "$env:PYTHON_VENV_PATH"'
    - python .\scripts\version.py -f .\SharedAssemblyInfo.cs
    # Build solution
    - '& "$env:NUGET_PATH" restore'
    - '& "$env:MSBUILD_PATH" /p:Configuration=Release /p:Platform=x86 /clp:ErrorsOnly'
    # Build gRPC stubs for Python client in examples directory
    - python -m grpc_tools.protoc ./Service/protos/step7.proto -I ./Service/protos
      --python_out=./examples/python --grpc_python_out=./examples/python
  artifacts:
    paths:
      - '.\s7cli\bin\x86\Release\'
      - '.\Server\bin\x86\Release\'
      - '.\UnitTests_s7cli\bin\x86\Release\'
      - '.\examples\python\'

test_job:
  stage: test
  script:
    - '& "$env:VSTEST_PATH" .\UnitTests_s7cli\bin\x86\Release\UnitTests_s7cli.dll'
  dependencies:
    - build_job
