variables:
  NUGET_PATH: 'C:\Tools\Nuget\nuget.exe'
  MSBUILD_PATH: 'C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\MSBuild.exe'
  PYTHON_VENV_PATH: 'C:\Tools\venv\Scripts\activate.ps1'
  VSTEST_PATH: 'C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\Extensions\TestPlatform\vstest.console.exe'

stages:
  - build
  - test

build_job:
  stage: build
  script:
    # Generate correct shared assembly version configuration
    - '& "$env:PYTHON_VENV_PATH"'
    - python .\scripts\version.py -f .\SharedAssemblyInfo.cs
    # Build solution
    - '& "$env:NUGET_PATH" restore'
    - '& "$env:MSBUILD_PATH" /p:Configuration=Release /p:Platform=x86 /clp:ErrorsOnly'
    # Build gRPC stubs for Python
    - python -m grpc_tools.protoc ./S7Service/protos/s7service/step7.proto
      -I ./S7Service/protos/
      --python_out=./S7Service/Python/
      --grpc_python_out=./S7Service/Python/
    # Build Python s7service package with setuptools
    - cd ./S7Service/Python/
    - python setup.py sdist bdist_wheel
  artifacts:
    paths:
      # Library
      - '.\S7Lib\bin\Release\'
      - '.\S7LibTests\bin\Release\'
      # CLI
      - '.\S7Cli\bin\Release\'
      - '.\S7CliTests\bin\Release\'
      # gRPC C# server
      - '.\S7Server\bin\Release\'
      - .\S7ServerTests\bin\x86\Release\
      # gRPC S7Service stubs
      - '.\S7Service\Python\'

test_job:
  stage: test
  script:
    - '& "$env:VSTEST_PATH" .\S7CliTests\bin\Release\S7CliTests.dll'
    - '& "$env:VSTEST_PATH" .\S7ServerTests\bin\x86\Release\net6.0\S7ServerTests.dll'
    # Skip experimental features test
    - '& "$env:VSTEST_PATH" .\S7LibTests\bin\Release\S7LibTests.dll /Tests:TestS7Handle'
  dependencies:
    - build_job
